### ISSUE TITLE
Combine with nicescad

### ISSUE THREAD

**Issue by WolfgangFahl** [jeff-dh/SolidPython#34] opened 2023-07-29 05:22 UTC
http://nicescad.bitplan.com/ allows to render openscad files and edit them in a browser (with pointers to many other similar solutions). I'd love to integrated SolidPython and nicescad to a convenient solution. I think things would not be too hard in nicescads local mode with full access to the local computer. For the server version i'd be a bit afraid to run python code which is supplied by user input.

**Comment by jeff-dh** [comment] 2023-07-29 21:16
Concerning sandboxing python code: are you aware of pyodide? Could it maybe solve the issue?

A very brief test with pyodide revealed that you can't import the current solid2 pypi package, because the platform is unknown to solid2, but when we disable the pickle cache and don't try to render the stl file with solid2, I assume it would work.

**Comment by jeff-dh** [comment] 2023-07-29 21:31
Hah, here is the current solidpython2 package from pypi running in pyodide (https://pyodide.org/en/latest/console.html) with a little hack ;)

```python
>>> import micropip
>>> await micropip.install("solidpython2")
>>> import platform
>>> platform.system = lambda: "Linux"
>>> from solid2 import *
>>> cube(2).left(10).up(5) - sphere(1).right(1).down(1)
difference() {
    translate(v = [0, 0, 5]) {
        translate(v = [-10, 0, 0]) {
            cube(size = 2);
        }
    }
    translate(v = [0, 0, -1]) {
        translate(v = [1, 0, 0]) {
            sphere(r = 1);
        }
    }
}
>>> 
```

**Comment by jeff-dh** [comment] 2023-07-29 22:35
I guess this is what you probably want:

https://gist.github.com/jeff-dh/c94b0727854432a014c1bdc24dad1c8a

**Comment by WolfgangFahl** [comment] 2023-07-30 05:34
@jeff-dh  - thank you for looking into this. Indeed i never tried https://pyodide.org/en/stable/ and trying out
```python
import micropip
await micropip.install("solidpython2")
import platform
platform.system = lambda: "Linux"
from solid2 import *
cube(2).left(10).up(5) - sphere(1).right(1).down(1)
```
in https://pyodide.org/en/latest/console.html immediately gave the output
```scad
difference() {
    translate(v = [0, 0, 5]) {
        translate(v = [-10, 0, 0]) {
            cube(size = 2);
        }
    }
    translate(v = [0, 0, -1]) {
        translate(v = [1, 0, 0]) {
            sphere(r = 1);
        }
    }
}
```
Your gist also runs nicely see [codepen for gist](https://codepen.io/seppl2019/pen/eYQQQwv)

Installing nicescad or running openscad in the browser is obviously not possible. The issue of converting SolidPython code to openscad might be solveable with this approach if we e.g. make this a restful service in a docker instance.

**Comment by WolfgangFahl** [comment] 2023-07-31 11:40
The preparations for integration are underway. With the dockerized version available at https://github.com/WolfgangFahl/nicescad/tree/main/docker, you can now execute a single Docker Compose command, granting you access to nicescad, openscad, blockscad, openjscad, and a conversion page simultaneously. But where do we go from here?

Currently, most SolidPython examples seem to conflate the concerns of creation and rendering. I would prefer a clear definition of the design (predominantly in variable 'd'). The rendering of this design (e.g., in stl/png), along with its OpenSCAD code, should be distinct.

At present, I'm contemplating providing the metadata for the design in a JSON format. I believe this is a crucial step towards delivering proper "components," as I'd love to mix and match components from different sources, particularly openscad/blockscad/solidpython. OpenJSCAD, however, appears to be less integration-friendly.

Especially when considering designs that are publicly available on platforms like Thingiverse, the component issue becomes significant. I propose that we create a discussion or issue regarding the component problem. Where would be your preferred location for this? Would you prefer it here at nicescad, or elsewhere? As an issue or as a discussion/blog entry...?

**Comment by jeff-dh** [comment] 2023-08-08 11:45
I'll close this, because this seems to me like a nicescad issue and as such is a duplicate of WolfgangFahl/nicescad/issues/28

**Closed as completed by jeff-dh** 2023-08-08 11:45 UTC
